version: '3.7'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test_db
    networks:
      - freecodecamp
networks:
  freecodecamp:

