version: '3.7'
services:
  dev-db:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Omer@2015
    networks:
      - freecodecamp
networks:
  freecodecamp:

